# This workflow will build Python packages on every commit.

name: Build archinstall

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: archlinux:latest
      options: --privileged
      volumes:
        - /etc/machine-id:/etc/machine-id

    steps:
    - uses: actions/checkout@v3
    - name: Initialize Pacman keyring
      run: pacman-key --init
    - name: Upgrade system and install packages
      run: pacman -Syu --noconfirm python python-build python-installer python-setuptools python-wheel python-pyparted
    - name: Build archinstall
      run: python -m build --wheel --no-isolation
    - name: Install archinstall
      run: python -m installer dist/*.whl
    - name: Run archinstall
      run: |
        python -V
        archinstall --script guided -v
        archinstall --script swiss -v
        archinstall --script only_hd -v
        archinstall --script minimal -v
    - name: Test archinstall
      run: |
        truncate -s 5G testimage.img
        losetup -f -P ./testimage.img
        archinstall --config examples/config-test.json --creds examples/creds-sample.json --silent
    - uses: actions/upload-artifact@v3
      with:
        name: archinstall
        path: dist/*
